### PR TITLE
Github ~> GitHub

### PR DESCRIPTION
**Pull request by parkr**
Just passing by...

😁

### CODE REVIEW

**Comment by parkr** [comment]
@chrisbolin Hey! I just realized that you do not watch this repository. Feel free to take this contribution or leave it. I'll close in the next week or so if it's not merged. 😄

**Comment by chrisbolin** [comment]
How did I manage to not watch my own repository?? Oh man. Thanks @parkr!

**Comment by chrisbolin** [comment]
i must have pressed this dangerous button at some point 
image

**Comment by chrisbolin** [comment]
i'm so curious @parkr, how did you run across this repo?

**Comment by parkr** [comment]
Hey, @chrisbolin! Thanks for merging. I came across the published page after seeing your [offline page](https://chris.bolin.co/offline/), which I thought was neat. Bounced around your website for a bit and noticed a teeny typo I figured I would propose the fix for 😄

**Comment by chrisbolin** [comment]
and now, through the magic of GitHub, it's *already live* :) https://chris.bolin.co/enchiridion/

**Pull request merged**
